# Generated by Django 3.2.7 on 2021-09-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_addproduct'),
        ('masters', '0003_auto_20210923_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='HSNCode',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
