# Generated by Django 3.2.7 on 2021-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_category_color_hsncode_package_size_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='style',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
