# Generated by Django 3.2.7 on 2021-09-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_addproduct_category'),
        ('masters', '0002_alter_hsncode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
