# Generated by Django 3.2.7 on 2021-09-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_addproduct_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddProduct',
        ),
    ]
