# Generated by Django 3.2.7 on 2021-09-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_addproduct_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='category',
        ),
    ]
